### ISSUE TITLE
declare module emailjs not working anymore when upgrading to 4.

### ISSUE THREAD

**Issue by ticlaudeberube** [emailjs-com/emailjs-nodejs#5]
import emailjs, { EmailJSResponseStatus } from '@emailjs/nodejs';
declare module 'emailjs';

    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "allowUmdGlobalAccess": true,
    
    Removed module declaration without success.

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\fichiers de claude\workspace\ipsofacto-express-website\node_modules\@emailjs\nodejs\mjs\models\EmailJSResponseStatus' imported from D:\fichiers de claude\workspace\ipsofacto-express-website\node_modules\@emailjs\nodejs\mjs\index.js

**Comment by xr0master** [comment]
Please try the version 5. It should be fixed.

**Comment by ticlaudeberube** [comment]
Sure, indeed works now.

Claude Bérubé
Lean-Agile developer
Communications Ipso Facto interactives <https://www.ipsofactointeractif.ca/>
***@***.***
514-529-0338





Le lun. 21 oct. 2024, à 11 h 43, xr0master ***@***.***> a
écrit :
